import React from 'react'
import { ProductView } from '../../../components/products/ProductView';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: "All Products",
  description: "Generated by create next app",
};

const Products = async() => {
  const response = await fetch("https://fakestoreapi.com/products", {
    next: { revalidate: 60 },
  });
  const data = await response.json()
  return (
    <div>
      <ProductView data={data}/>
    </div>
  )
}

export default Products